colname: 'creat_68'
y_col: 'creat_72'
cols_to_drop: ['id']
per_colname: ''
per_cols: ['', '']
keep: ''
sample_size: 300
compare_col: 'group'
compare_vals: [1, 2, 3]
compare_labels: ['Visit 1', 'Visit 2', 'Visit 3']
